config/routes.rb
Rails.application.routes.draw do
  resources :users
    # Back admin routes start
    namespace :admin do
      resources :input_files, only: [:new, :create, :index, :destroy, :update]
      resources :processing_scripts, only: [:new, :create, :index, :destroy, :update]
      resources :processing_results

      resources :users
  
      # Admin root
      root to: 'application#index'
    end
    # Back admin routes end
  
    # Front routes start
    devise_for :users, only: [:session, :registration, :confirmation], path: 'session',
               path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
    # Application root
    root to: "admin/input_files#index"
    # Front routes end
end

app/models/input_file.rb
class InputFile < ApplicationRecord
  has_one_attached :file

  validates :file, presence: true

  def file_on_disk
    ActiveStorage::Blob.service.send(:path_for, file.key)
  end
end

app/controllers/admin/input_files_controller.rb
class Admin::InputFilesController < Admin::ApplicationController
  
  def index
    @input_files = InputFile.order("id DESC")
  end  

  def new
    @input_file = InputFile.new
  end  

  def create
    @input_file = InputFile.new(permitted_params)
    if @input_file.save
      redirect_to admin_input_files_path, notice: "File has been successfully added"
    else
      render :new
    end  
  end  

  def destroy
    @input_file = InputFile.find(params[:id])
    if @input_file.destroy
      redirect_to admin_input_files_path, notice: "File has been successfully deleted"
    else
      redirect_to admin_input_files_path, error: "Unable to remove the file"
    end    
  end  


  private 

  def permitted_params
    params.require(:input_file).permit(:file)
  end  


end    

app/views/admin/input_files/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">List of Input Files</h3>
        </div>

        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTable" role="grid">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Uploaded</th>
                      <th class="col-xs-1">Actions</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @input_files.each do |file| %>
                      <tr>
                        <td> <%= link_to file.file.filename.to_s, rails_blob_path(file.file, disposition: :attachment, only_path: true) %> </td>
                        <td> <%=l file.created_at, format: :long %> </td>
                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-cog"></i>'), admin_processing_results_url(id: file.id), class: 'btn btn-sm btn-warning', method: :post, 
                            data: {confirm: 'Are you sure you want to process this file?' } %>
                            <%= link_to raw('<i class="fa fa-trash"></i>'), admin_input_file_url(file), class: 'btn btn-sm btn-danger', method: :delete,
                                            data: { confirm: 'Are you sure you want to delete this element?' } %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                  <tfoot>
                    <tr role="row">
                      <th>Name</th>
                      <th>Uploaded</th>
                      <th class="col-xs-1">Actions</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to 'New Input File', new_admin_input_file_path, class: 'btn btn-success pull-right' %>
  </div>
</div>

app/views/admin/input_files/new.html.erb
 <div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Add new input file</h3>
        </div>

        <div class="box-body">
         <%= form_for @input_file, url: admin_input_files_path, html: {
           onsubmit: "if ($('input#input_file_file').val() === '') { alert('You must choose a file'); return false;}"
         } do |f| %>
            <div class="box-body col-4">
              <h4>Please click button below to start</h4>
          <p>
            <div class="custom-file" id="customFile" lang="es">
              <%= f.file_field :file, class: "custom-file-input "%>
              <label class="custom-file-label" for="exampleInputFile">
                Please select sequences file and click save below
              </label>
              <p>
                <button type="submit" id="submit-form" 
                class="btn bg-maroon btn-flat margin" 
                >SAVE</button>
              </p>

            </div>
          </p>
         <% end %>
        </div>

        </div>
    </div>
</div>
<%= content_for :added_scripts do %>
<script type="text/javascript">

<script>
<% end %>