config/routes.rb
Rails.application.routes.draw do
  resources :users
    # Back admin routes start
    namespace :admin do
      resources :input_files, only: [:new, :create, :index, :destroy, :update]
      resources :processing_scripts, only: [:new, :create, :index, :destroy, :update]
      resources :processing_results

      resources :users
  
      # Admin root
      root to: 'application#index'
    end
    # Back admin routes end
  
    # Front routes start
    devise_for :users, only: [:session, :registration, :confirmation], path: 'session',
               path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
    # Application root
    root to: "admin/input_files#index"
    # Front routes end
end

app/models/processing_script.rb
class ProcessingScript < ApplicationRecord
  has_one_attached :file

  has_many :processing_results
  
  scope :active, -> { where(active: true) }

  def file_on_disk
    ActiveStorage::Blob.service.send(:path_for, file.key)
  end  
end

app/controllers/admin/processing_scripts_controller.rb
class Admin::ProcessingScriptsController < Admin::ApplicationController
  
    def index
      @processing_scripts = ProcessingScript.order("id DESC")
    end  
  
    def new
      @processing_script = ProcessingScript.new
    end  

    def update
      @processing_script = ProcessingScript.find(params[:id])
      @processing_script.update_column(:active, true)
      ProcessingScript.where("id <> ?", @processing_script.id).update_all(active: false) if @processing_script.active?
      redirect_to admin_processing_scripts_path, notice: "Script has been successfully marked as active"
    end    
  
    def create
      @processing_script = ProcessingScript.new(permitted_params)
      
      @processing_script.active 
      if @processing_script.save
        ProcessingScript.where("id <> ?", @processing_script.id).update_all(active: false) if @processing_script.active?
        redirect_to admin_processing_scripts_path, notice: "Script has been successfully added"
      else
        render :new
      end  
    end  
  
    def destroy
      @processing_script = ProcessingScript.find(params[:id])
      if @processing_script.destroy
        redirect_to admin_processing_scripts_path, notice: "Script has been successfully deleted"
      else
        redirect_to admin_processing_scripts_path, error: "Unable to remove this script"
      end    
    end  
  
    private 
  
    def permitted_params
      params.require(:processing_script).permit(:file, :active)
    end  
  
  
  end    

app/views/admin/processing_scripts/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">List of Processing Scripts</h3>
        </div>

        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTable" role="grid">
                  <thead>
                    <tr>
                      <th>Script</th>
                      <th>Active?</th>
                      <th>Uploaded</th>
                      <th class="col-xs-1">Actions</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @processing_scripts.each do |file| %>
                      <tr>
                        <td> <%= link_to file.file.filename.to_s, rails_blob_path(file.file, disposition: :attachment, only_path: true) %> </td>
                        <td> <%=  file.active %> </td>
                        <td> <%=l file.created_at, format: :long %> </td>
                        <td>
                          <div class="btn-row">
                          <% unless file.active %>
                            <%= link_to raw('<i class="fa fa-cog"></i>'), admin_processing_script_path(file), class: 'btn btn-sm btn-warning', method: :patch,
                                            data: { confirm: 'Are you sure you want to activate this scirpt? (it will deactivate others)' } %>
                          <% end %>
                           <% unless @processing_scripts.pluck(:id).count == 1  %>
                            <%= link_to raw('<i class="fa fa-trash"></i>'), admin_processing_script_url(file), class: 'btn btn-sm btn-danger', method: :delete,
                                            data: { confirm: 'Are you sure you want to delete this element?' } %>
                            <% end %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                  <tfoot>
                    <tr role="row">
                      <th>Name</th>
                      <th>Active?</th>
                      <th class="col-xs-1">Actions</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to 'New Processign Script', new_admin_processing_script_path, class: 'btn btn-success pull-right' %>
  </div>
</div>

app/views/admin/processing_scripts/new.html.erb
 <div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Add new processing script</h3>
        </div>

        <div class="box-body">
         <%= form_for @processing_script, url: "/admin/processing_scripts", html: {
           onsubmit: "if ($('input#processing_script_file').val() === '') { alert('You must choose a file'); return false;}"
         } do |f| %>
            <div class="box-body col-4">
              <h4>Please select a file</h4>
          <p>
            <div class="custom-file" id="customFile" lang="es">
              <%= f.file_field :file, class: "custom-file-input "%>
              <label class="custom-file-label" for="exampleInputFile">
                Please select processing script file and click save below
              </label>
              <p>
              <div class="custom-file">
                <%= f.check_box :active, {}, value: "true", checked: false%>
               <label>Make active</label>
              </div>
                <button type="submit" id="submit-form" 
                class="btn bg-maroon btn-flat margin" 
                >SAVE</button>
              </p>
             
            </div>
              
          </p>
         <% end %>
        </div>

        </div>
    </div>
</div>
<%= content_for :added_scripts do %>
<script type="text/javascript">

<script>
<% end %>