config/routes.rb
Rails.application.routes.draw do
  resources :users
    # Back admin routes start
    namespace :admin do
      resources :input_files, only: [:new, :create, :index, :destroy, :update]
      resources :processing_scripts, only: [:new, :create, :index, :destroy, :update]
      resources :processing_results

      resources :users
  
      # Admin root
      root to: 'application#index'
    end
    # Back admin routes end
  
    # Front routes start
    devise_for :users, only: [:session, :registration, :confirmation], path: 'session',
               path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
    # Application root
    root to: "admin/input_files#index"
    # Front routes end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    respond_to :json, :html
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end

    # GET /users/1
    # GET /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
      @url = admin_users_path
    end

    # GET /users/1/edit
    def edit
      @url = admin_user_path(@user)
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      if @user.save
        flash[:notice] = t('admin.users.create.success')
        respond_with :edit, :admin, @user
      else
        flash[:warning] = @user.errors.full_messages.uniq.join(', ')
        respond_with :new, :admin, :user
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      if @user.update(user_params)
        flash[:notice] = t('admin.users.update.success')
        respond_with :edit, :admin, @user
      else
        flash[:warning] = @user.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :user
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_path, notice: t('admin.users.destroy.success') }
        format.json { head :no_content }
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    private def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/views/admin/users/_form.html.erb
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control", placeholder: "Enter email", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control", placeholder: "Enter password", required: (@user.new_record? ? true : false) %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password", required: (@user.new_record? ? true : false) %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter name", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

app/views/admin/users/edit.html.erb
<%= form_for @user, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Edit User</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/users/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_users_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">List of Users</h3>
        </div>

        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTable" role="grid">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Email</th>
                      <th class="col-xs-1">Actions</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @users.each do |user| %>
                      <tr>
                        <td> <%= user.name %> </td>
                        <td> <%= user.email %> </td>
                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-cogs"></i>'), edit_admin_user_url(user), class: 'btn btn-sm btn-warning' %>
                            <%= link_to raw('<i class="fa fa-trash"></i>'), admin_user_url(user), class: 'btn btn-sm btn-danger', method: :delete,
                                            data: { confirm: 'Are you sure you want to delete this element?' } unless current_user.id == user.id  %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                  <tfoot>
                    <tr role="row">
                      <th>Name</th>
                      <th>Email</th>
                      <th class="col-xs-1">Actions</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to 'New User', new_admin_user_path, class: 'btn btn-success pull-right' %>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= form_for @user, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">New User</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/users/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_users_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>