config/routes.rb
Rails.application.routes.draw do
  resources :users
    # Back admin routes start
    namespace :admin do
      resources :input_files, only: [:new, :create, :index, :destroy, :update]
      resources :processing_scripts, only: [:new, :create, :index, :destroy, :update]
      resources :processing_results

      resources :users
  
      # Admin root
      root to: 'application#index'
    end
    # Back admin routes end
  
    # Front routes start
    devise_for :users, only: [:session, :registration, :confirmation], path: 'session',
               path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
    # Application root
    root to: "admin/input_files#index"
    # Front routes end
end

app/views/admin/shared/_content_header.html.erb
<section class="content-header">
  <h1> <%= params[:controller].split('/').last.humanize %> </h1>
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-dashboard"></i> Home'.html_safe, admin_root_path %></li>
    <li class="active"> <%= params[:controller].split('/').last.humanize %> </li>
  </ol>
</section>

app/views/admin/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.0
  </div>
</footer>

app/views/admin/shared/_header.html.erb
<header class="main-header">
  <%= content_tag :a, href: admin_root_path, class: 'logo' do %>
    <span class="logo-mini">
    <b>S</b>DB</span>
    <span class="logo-lg">
    <b>Sequences</b>DB</span>
  <% end %>

  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "http://placehold.it/160x160", class: "user-image" %>
            <span class="hidden-xs"><%= current_user.name %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <%= image_tag "http://placehold.it/160x160", class: "img-circle" %>

              <p>
                <%= current_user.name %>
                <small>Member since <%= current_user.created_at.strftime("%B, %Y") %></small>
              </p>
            </li>

            <li class="user-footer">
              <div class="pull-left">
                <%= link_to 'Profile', edit_admin_user_path(current_user), class: 'btn btn-default -btn-flat' %>
              </div>
              <div class="pull-right">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/admin/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h4>
        <i class="icon fa fa-<%= name.to_s == 'notice' ? 'check' : 'ban' %>"></i> 
        <%= name.to_s == 'notice' ? 'Success!' : 'Alert!' %>
      </h4>
      <%= content_tag :div, raw(msg.split(",").join("<br>").html_safe), :id => "flash_#{name}" %>
    </div>
    <% flash[name] = nil %>
  <% end %>
<% end %>

app/views/admin/shared/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">

    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "http://placehold.it/160x160", class: "img-circle" %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <%= link_to '<i class="fa fa-circle text-success"></i><span>Online</span>'.html_safe, admin_root_path %>
      </div>
    </div>
    <ul class="sidebar-menu">
      <li class="header"><%= t('admin.sidebar.main_navigation') %></li>
      <li> <%= link_to '<i class="fa fa-dashboard"></i><span>Dashboard</span>'.html_safe, admin_root_path %> </li>

      <li class="header"><%= t('admin.sidebar.administration') %></li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-file"></i>
          <span>Input Files</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-download"></i> Input Files'.html_safe, admin_input_files_path %> </li>
          <li> <%= link_to '<i class="fa fa-file-o"></i> New file'.html_safe, new_admin_input_file_path %> </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-file"></i>
          <span>Processing Scripts</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-file-o"></i> Processing Scripts'.html_safe, admin_processing_scripts_path %> </li>
          <li> <%= link_to '<i class="fa fa-code"></i> New Processing Script'.html_safe, new_admin_processing_script_path %> </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-file"></i>
          <span>Processing Results</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-list-alt"></i> Processing Results'.html_safe, admin_processing_results_path %> </li>
        </ul>
      </li>

      <li class="treeview">
        <a href="#">
          <i class="fa fa-users"></i>
          <span>Users</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-circle-o"></i> List Users'.html_safe, admin_users_path %> </li>
          <li> <%= link_to '<i class="fa fa-circle-o"></i> Create User'.html_safe, new_admin_user_path %> </li>
        </ul>
      </li>

    </ul>

  </section>
</aside>